Update list-repositories.yml

diff --git a/.github/workflows/list-repositories.yml b/.github/workflows/list-repositories.yml
--- a/.github/workflows/list-repositories.yml
+++ b/.github/workflows/list-repositories.yml
@@ -88,7 +88,10 @@ jobs:
 
           # Check the content of assets/img directory in each repository
           echo "Cloning repository '$title' to check assets/img directory..."
-          git clone --depth=1 "https://github.com/mpek29/$title.git" "$title"
+          if ! git clone --depth=1 "https://github.com/mpek29/$title.git" "$title"; then
+            echo "⚠️ Failed to clone repository '$title'. Continuing with the next repository..."
+            continue  # Skip to the next repository
+          fi
 
           img_dir="$title/assets/img"
 
